#services:
#  mongodb:
#    image: mongo
#    container_name: mongo_db
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=password
#
#  mongo-express:
#    image: mongo-express
#    container_name: mongo_express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#
#  eventHub:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: eventhub:1.1
#    container_name: eventhub
#    links:
#      - mongodb
#volumes:
#  mongo: {}
