version: '3.3'
services:

  hive:
    image: 'hive'
    build:
      context: .
    container_name: hive
#    ports:
#      - "5001:5001"
#    networks:
#      - hive-mysql
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      restart: on-failure:3
      restart_delay: 20s


  db:
    image: mysql:8
#    networks:
#      - hive-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3303:3306'
    expose:
      # Opens port 3306 on the container
      - '3303'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

#networks:
#  hive-mysql: