name: Build & Deploy app
on:
  push:
    branches:
      - master
      - develop
      - ERC-5
  pull_request:
    branches:
      - develop
jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the app
        run: mvn -DskipTests package
