name: Build and Deploy EventHub to Microsoft Azure

on:
  push:
    branches:
      - dev

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  JAVA_VERSION: 17
  AZURE_SUBSCRIPTION: 1f04183e-06ad-4de3-806d-3bdf8a517766
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  test:
    needs: build
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/eventhub:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/eventhub:${{ github.sha }}

#      - name: Log in to registry
#        uses: docker/login-action@v2
#        with:
#          registry: https://index.docker.io/v1/
#          username: ${{ secrets.AzureAppService_ContainerUsername_80213be1ea454926990c34c388a8b82e }}
#          password: ${{ secrets.AzureAppService_ContainerPassword_9e913184015649309f5962445461b632 }}
#
#      - name: Build and push container image to registry
#        uses: docker/build-push-action@v3
#        with:
#          push: true
#          tags: index.docker.io/mhisterjhay/eventhub:${{ github.sha }}
#          context: .
#          file: ./Dockerfile
#
#
#      - name: Deploy to Azure Web App
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: 'event-hub-java'
#          slot-name: 'production'
#          publish-profile: ${{ secrets.AzureAppService_PublishProfile_3df6f7f11471446cb24ee1880a8f228c }}
#          images: 'index.docker.io/mhisterjhay/eventhub:${{ github.sha }}'
#


